name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: test
      run: make test
